// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMg4M2VcIQKllw9fAYVAdnvFppFUGxyQA',
    appId: '1:340889079632:web:2ecc2bcc90b129e8d5a655',
    messagingSenderId: '340889079632',
    projectId: 'dynup-d424c',
    authDomain: 'dynup-d424c.firebaseapp.com',
    storageBucket: 'dynup-d424c.firebasestorage.app',
    measurementId: 'G-HEP7V5QS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PUxqiKlF7XWk5nT70RvwmEgf-VZi1ZE',
    appId: '1:340889079632:android:2e05ffa6a95f9dd1d5a655',
    messagingSenderId: '340889079632',
    projectId: 'dynup-d424c',
    storageBucket: 'dynup-d424c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAsOh5w9V7Yf6iG4VARnOsYW2gtCBOM6g',
    appId: '1:340889079632:ios:74eadf078032fd53d5a655',
    messagingSenderId: '340889079632',
    projectId: 'dynup-d424c',
    storageBucket: 'dynup-d424c.firebasestorage.app',
    iosBundleId: 'com.example.shahabfit',
  );
}
